org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5

# Mod Properties
mod_version=0.0.1
maven_group=dev.redrain0o0
archives_base_name=LegacyVR

# Dependencies
fabric_version=0.155.2+26.1.2
factory_api_version=2.2.8
legacy4j_version=1.9
vivecraft_version=1.3.15